FROM openjdk17-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application JAR file to the container
COPY ./target/challengean-0.0.1-SNAPSHOT.jar app.jar

# Expose the desired ports
EXPOSE 8181

# Launch the application when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]